-- Create hidden_categories table
create table hidden_categories (
  id bigint generated by default as identity primary key,
  category_id bigint references categories(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(category_id, user_id)
);

-- Enable RLS
alter table hidden_categories enable row level security;

-- Create policy to allow users to hide categories
create policy "Users can hide categories"
  on hidden_categories for insert
  to authenticated
  with check (
    auth.uid() = user_id
  );

-- Create policy to allow users to see their hidden categories
create policy "Users can see their hidden categories"
  on hidden_categories for select
  to authenticated
  using (
    auth.uid() = user_id
  );

-- Create policy to allow users to unhide categories
create policy "Users can unhide categories"
  on hidden_categories for delete
  to authenticated
  using (
    auth.uid() = user_id
  );
