-- Add is_public column to categories table
ALTER TABLE categories ADD COLUMN is_public BOOLEAN NOT NULL DEFAULT false;

-- Create hidden_categories table
CREATE TABLE hidden_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, category_id)
);

-- Add RLS policies for hidden_categories
ALTER TABLE hidden_categories ENABLE ROW LEVEL SECURITY;

-- Policy to allow users to hide/unhide categories for themselves
CREATE POLICY "Users can manage their own hidden categories"
    ON hidden_categories
    FOR ALL
    USING (auth.uid() = user_id);

-- Policy to allow users to view their own hidden categories
CREATE POLICY "Users can view their own hidden categories"
    ON hidden_categories
    FOR SELECT
    USING (auth.uid() = user_id);
